modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Denmoth/MothLib/issues"

[[mods]]
modId="mothlib"
version="${mod_version}"
displayName="MothLib"
authors="Denmoth"
description='''Core library for Denmoth mods.'''

[[dependencies.mothlib]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mothlib]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},${minecraft_version_range_upper})"
ordering="NONE"
side="BOTH"

[[dependencies.mothlib]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="AFTER"
side="BOTH"